version: '3'

services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    ports:
      - "27018:27017"   # Expose MongoDB on standard port for db.ekowlabs.space
    networks:
      - backendnet

  backend:
    build:
      context: ./backend
    restart: always
    env_file:
      - ./.env
    expose:
      - "3000"
    networks:
      - backendnet
    depends_on:
      - mongo

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"  # Add HTTPS support
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro  # SSL certificates
    depends_on:
      - backend
    networks:
      - backendnet

volumes:
  mongo_data:

networks:
  backendnet:
    driver: bridge
