name: Deploy to VPS

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH and deploy
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519

        eval "$(ssh-agent -s)"
        echo "${{ secrets.SSH_PASSPHRASE }}" | ssh-add ~/.ssh/id_ed25519

        ssh-keyscan -H gcp.ekowlabs.space >> ~/.ssh/known_hosts

        # Test connection
        ssh -o StrictHostKeyChecking=no ekowfirmino@gcp.ekowlabs.space "echo SSH connection successful"

        # Create .env file with expanded secrets (no quotes to allow expansion)
        cat > .env << 'EOF'
        MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGO_INITDB_ROOT_USERNAME }}
        MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}
        NODE_ENV=${{ secrets.NODE_ENV }}
        PORT=${{ secrets.PORT }}
        MONGODB_URI=${{ secrets.MONGODB_URI }}
        APP_NAME=${{ secrets.APP_NAME }}
        EOF

        # Upload .env to VPS
        cat .env | ssh -o StrictHostKeyChecking=yes ekowfirmino@gcp.ekowlabs.space "cat > /tmp/.env"

        # Run deployment commands on VPS
        ssh -o StrictHostKeyChecking=yes ekowfirmino@gcp.ekowlabs.space bash -e << 'SSH_COMMANDS'
          cd /home/ekowfirmino

          if [ ! -d /home/ekowfirmino/docker/.git ]; then
            echo "Cloning repo for the first time..."
            git clone https://github.com/ekow1/docker.git /home/ekowfirmino/docker
          else
            echo "Pulling latest changes..."
            cd /home/ekowfirmino/docker
            git pull origin main
          fi

          mv /tmp/.env /home/ekowfirmino/docker/.env

          if ! command -v docker &> /dev/null; then
            echo "Installing Docker..."
            curl -fsSL https://get.docker.com -o get-docker.sh
            sudo sh get-docker.sh
            sudo usermod -aG docker ekowfirmino
            rm get-docker.sh
          fi

          if ! command -v docker-compose &> /dev/null; then
            echo "Installing Docker Compose..."
            sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
          fi

          cd /home/ekowfirmino/docker
          docker-compose down
          docker-compose up -d --build
          docker image prune -f
        SSH_COMMANDS 
 